Repository snek-shipyard/ohrwurm, pull requests merged in 2020-11, with the labels that each got.

#3 Update Wagtail dependency
  requirements/base.txt
Labels: kind/dependencies

#5 Add waveater module
  esite/waveater/__init__.py
  esite/waveater/admin.py
  esite/waveater/apps.py
  esite/waveater/download_from_url.py
  esite/waveater/file_handler.py
  esite/waveater/migrations/__init__.py
  esite/waveater/models.py
  esite/waveater/tests.py
  esite/waveater/views.py
Labels: dif/hard, effort/hours, kind/enhancement

#9 Add track app
  esite/bifrost/helpers.py
  esite/bifrost/schema.py
  esite/bifrost/types/structures.py
  esite/bifrost/utils.py
  esite/settings/base.py
  esite/track/__init__.py
  esite/track/admin.py
  esite/track/apps.py
  esite/track/blocks.py
  esite/track/migrations/0001_initial.py
  esite/track/migrations/__init__.py
  esite/track/models.py
  esite/track/schema.py
  esite/track/tests.py
  esite/track/validators.py
  esite/track/views.py
  esite/track/wagtail_hooks.py
  esite/user/admin.py
Labels: dif/hard, effort/days, kind/bug :bug:, kind/enhancement

#12 Add track app
  esite/bifrost/helpers.py
  esite/bifrost/schema.py
  esite/bifrost/types/structures.py
  esite/bifrost/utils.py
  esite/settings/base.py
  esite/track/__init__.py
  esite/track/admin.py
  esite/track/apps.py
  esite/track/blocks.py
  esite/track/migrations/0001_initial.py
  esite/track/migrations/__init__.py
  esite/track/models.py
  esite/track/schema.py
  esite/track/tests.py
  esite/track/validators.py
  esite/track/views.py
  esite/track/wagtail_hooks.py
  esite/user/admin.py
Labels: dif/hard, effort/days, kind/enhancement

#13 Add waveater app
  esite/waveater/__init__.py
  esite/waveater/admin.py
  esite/waveater/apps.py
  esite/waveater/download_from_url.py
  esite/waveater/file_handler.py
  esite/waveater/migrations/__init__.py
  esite/waveater/models.py
  esite/waveater/tests.py
  esite/waveater/views.py
Labels: dif/hard, effort/hours, kind/enhancement

#15 Add pac auth
  esite/bifrost/helpers.py
  esite/track/migrations/0001_initial.py
  esite/track/migrations/0002_projectaudiochannel_users.py
  esite/track/migrations/0003_auto_20201124_0257.py
  esite/track/models.py
  esite/track/schema.py
  esite/user/admin.py
  esite/user/migrations/0003_snekuser_telegram_user_id.py
  esite/user/models.py
  esite/user/schema.py
Labels: dif/hard, effort/hours, kind/bug :bug:, kind/enhancement

#20 018 add bifrost authentication support
  esite/bifrost/helpers.py
  esite/bifrost/schema.py
Labels: dif/easy, effort/hours, kind/bug :bug:

#21 Improve track app
  esite/settings/base.py
  esite/track/blocks.py
  esite/track/migrations/0004_auto_20201128_0004.py
  esite/track/models.py
Labels: dif/medium, effort/hours, kind/bug :bug:, kind/enhancement
